apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2  # The number of instances you want
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: faridadwanii/python-jenkins-app:latest  
        ports:
        - containerPort: 5000  # Replace with the port your app listens on
