apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 5000  # The port the service is exposed on
    targetPort: 5000  # The container port to forward to
    nodePort: 30016
  type: LoadBalancer
